import json
import os
import sys
from pathlib import Path

from material_color_utilities import Variant
from material_color_utilities import theme_from_image as m3_theme_from_image
from PIL import Image


KITTY_DIR = Path.home() / ".config" / "kitty"
CACHE_DIR = Path.home() / ".cache" / "wal"

WALLPAPER_STATE = Path.home() / ".cache" / "noctalia" / "wallpapers.json"


def detect_wallpaper() -> str | None:
    if not WALLPAPER_STATE.exists():
        return None
    try:
        data = json.loads(WALLPAPER_STATE.read_text())
        for monitor in data.get("wallpapers", {}).values():
            path = monitor.get("dark") or monitor.get("light")
            if path and Path(path).exists():
                return path
    except Exception:
        pass
    return None


def make_kitty_conf(scheme, source_hex: str) -> str:
    pp = scheme.primary_palette
    sp = scheme.secondary_palette
    tp = scheme.tertiary_palette
    np = scheme.neutral_palette
    ep = scheme.error_palette

    def t(palette, tone):
        return palette.get_argb(tone) & 0xFFFFFF

    bg = t(pp, 5)
    fg = t(np, 95)
    cursor = t(pp, 80)
    cursor_text = t(pp, 5)
    sel_bg = t(pp, 40)
    sel_fg = t(np, 95)
    url_col = t(pp, 70)
    border_active = t(pp, 60)
    border_inactive = t(np, 25)

    c0 = t(np, 10)
    c1 = t(ep, 60)
    c2 = t(sp, 55)
    c3 = t(tp, 65)
    c4 = t(pp, 55)
    c5 = t(tp, 65)
    c6 = t(sp, 65)
    c7 = t(np, 92)
    c8 = t(np, 30)
    c9 = t(ep, 75)
    c10 = t(sp, 75)
    c11 = t(tp, 80)
    c12 = t(pp, 75)
    c13 = t(tp, 80)
    c14 = t(sp, 80)
    c15 = t(np, 97)

    lines = [
        f"## Generated by wap-kitty (M3 TonalSpot)",
        f"## Source color: {source_hex}",
        "",
        f"foreground         #{fg:06x}",
        f"background         #{bg:06x}",
        f"cursor             #{cursor:06x}",
        f"cursor_text_color  #{cursor_text:06x}",
        f"selection_foreground #{sel_fg:06x}",
        f"selection_background #{sel_bg:06x}",
        f"url_color          #{url_col:06x}",
        f"active_border_color   #{border_active:06x}",
        f"inactive_border_color #{border_inactive:06x}",
        "",
    ]

    for i, c in enumerate([c0, c1, c2, c3, c4, c5, c6, c7]):
        lines.append(f"color{i}       #{c:06x}")
    lines.append("")
    for i, c in enumerate([c8, c9, c10, c11, c12, c13, c14, c15]):
        lines.append(f"color{i + 8}       #{c:06x}")
    lines.append("")

    lines += [
        f"active_tab_foreground     #{bg:06x}",
        f"active_tab_background     #{t(pp, 60):06x}",
        f"inactive_tab_foreground   #{t(np, 80):06x}",
        f"inactive_tab_background   #{t(np, 15):06x}",
    ]

    return "\n".join(lines) + "\n"


def apply(wallpaper: str) -> None:
    img = Image.open(wallpaper)
    theme = m3_theme_from_image(img, variant=Variant.TONALSPOT)
    dark = theme.schemes.dark

    source_hex = theme.source
    theme_content = make_kitty_conf(dark, source_hex)

    CACHE_DIR.mkdir(parents=True, exist_ok=True)
    (CACHE_DIR / "colors-kitty.conf").write_text(theme_content)

    KITTY_DIR.mkdir(parents=True, exist_ok=True)
    (KITTY_DIR / "current-theme.conf").write_text(theme_content)

    def c(palette, tone):
        return palette.get_argb(tone) & 0xFFFFFF

    pp = dark.primary_palette
    tp = dark.tertiary_palette
    np = dark.neutral_palette

    def block(hex_color: int) -> str:
        r = (hex_color >> 16) & 0xFF
        g = (hex_color >> 8) & 0xFF
        b = hex_color & 0xFF
        return f"\033[48;2;{r};{g};{b}m  \033[0m"

    primary = c(pp, 55)
    secondary = c(dark.secondary_palette, 55)
    tertiary = c(tp, 65)
    fg = c(np, 95)
    bg = c(np, 10)

    print(f"  Wallpaper: {wallpaper}")
    print(f"  Source:    {source_hex}")
    print(f"  {block(primary)} Primary   #{primary:06x}")
    print(f"  {block(secondary)} Secondary #{secondary:06x}")
    print(f"  {block(tertiary)} Tertiary  #{tertiary:06x}")
    print(f"  {block(fg)} Foreground #{fg:06x}")
    print(f"  {block(bg)} Background #{bg:06x}")
    print()


def main() -> None:
    wallpaper = sys.argv[1] if len(sys.argv) > 1 else detect_wallpaper()

    if not wallpaper:
        print("Usage: wap [image]")
        print("  Without args - auto-detect wallpaper from noctalia")
        sys.exit(1)

    if not os.path.isfile(wallpaper):
        print(f"File not found: {wallpaper}")
        sys.exit(1)

    apply(wallpaper)
    print("Done")
